version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    container_name: rag-api
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/app
    ports:
      - ${API_PORT:-8000}:8000
    depends_on:
      pgsql:
        condition: service_healthy
      chromadb:
        condition: service_healthy
      ollama:
        condition: service_healthy
    networks:
      - rag
  pgsql:
    container_name: rag-pgsql
    image: postgres:17.3-alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT:-5432}:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rag
  pgadmin:
    container_name: rag-pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_PORT:-5050}:80
    depends_on:
      - pgsql
    networks:
      - rag
  ollama:
    build:
      context: .
      dockerfile: docker/ollama/Dockerfile
    container_name: ollama
    volumes:
      - ollama_model:/root/.ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    healthcheck:
      test: ollama list || exit 1
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - rag
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  chromadb:
    image: chromadb/chroma:0.6.3
    container_name: chromadb
    volumes:
      - chromadb_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-FALSE}
      - ALLOW_RESET=TRUE
    ports:
      - "${CHROMADB_PORT:-8001}:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - rag
volumes:
  postgres_data:
  chromadb_data:
  ollama_model:
networks:
  rag:
    driver: bridge